<!--BEGIN FOOTER-->
<footer role="footer">
	<section role="copyright">
	  <p class="quiet">Powered by <a href="http://html5strappr.com">HTML5 Strappr</a></p>
	</section>
</footer>
<!-- plugins -->
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.6.2/jquery.min.js"></script>
<script>window.jQuery || document.write('<script src="/javascripts/jquery-1.6.2.min.js"><\/script>')</script>
<!--script src="/lib/javascripts/hashgrid.js"></script--> 
<script src="/lib/javascripts/jquery.placeholder.min.js"></script>
<script src="/lib/javascripts/jquery.respond.min.js"></script>
<!-- custom scripts -->
<!--script src="/lib/javascripts/ggs.js"></script> uncomment to use GGS grid overlay -->
<script src="/lib/javascripts/hashgrid.js"></script> 
<script src="/lib/javascripts/base.js"></script> 