<!--BEGIN FOOTER-->
<footer role="footer">
	<section role="meta">
		<div class="wrapper">
	    <div role="books">
	      <h3>Books By Todd</h3>
	      <ul>
	        <li>
	        	<a href="http://bit.ly/protobk">
							<b>P</b> 
							Prototyping: A Practitioner's Guide <em>Rosenfeld Media</em>
						</a>
	        </li>
	        <li>
	        	<a href="http://bit.ly/guxbk">
							<b>G</b> 
							Guerrilla UX Methods <em>Morgann Kaufman</em>
						</a>
	        </li>
	      </ul>
			</div>
	    <div role="social">
	      <h3>Connect</h3>
	      <ul>
	        <li>
	        	<a href="http://twitter.com/zakiwarfel/">
							<b>T</b> Twitter
						</a>
					</li>
	        <li>
	        	<a href="http://dribbble.com/zakiwarfel/">
							<b>D</b> Dribbble
						</a>
					</li>
	        <li>
	        	<a href="http://pinterest.com/zakiwarfel/">
							<b>P</b> Pinterest
						</a>
					</li>
	        <li>
	        	<a href="http://vimeo.com/zakiwarfel/">
							<b>V</b> Vimeo
						</a>
					</li>
	        <li>
	        	<a href="http://foursquare.com/zakiwarfel/">
							<b>F</b> Foursquare
						</a>
					</li>
	        <li>
	        	<a href="http://www.last.fm/user/zakiwarfel">
							<b>L</b> Last.fm
						</a>
					</li>
	      </ul>
			</div>
		</div>
	</section>
	<section role="copyright">
	  <ul>
	    <li><cite>Powered by Hand Coded Craftsmanship.</cite></li>
	    <li>Copyright © 1996-2012 <a href="http://zakiwarfel.com"><em>zw</em></a>. Stealing isn't cool.</li>
	  </ul>
	</section>
</footer>
<!-- plugins -->
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.6.2/jquery.min.js"></script>
<script>window.jQuery || document.write('<script src="/javascripts/jquery-1.6.2.min.js"><\/script>')</script>
<!--script src="/lib/javascripts/hashgrid.js"></script--> 
<script src="/lib/javascripts/jquery.placeholder.min.js"></script>
<script src="/lib/javascripts/jquery.respond.min.js"></script>
<!-- custom scripts -->
<!--script src="/lib/javascripts/ggs.js"></script> uncomment to use GGS grid overlay -->
<script src="/lib/javascripts/hashgrid.js"></script> 
<script src="/lib/javascripts/base.js"></script> 