<!--BEGIN FOOTER-->
<footer id="StickyFooter">
	<div class="wrapper">
		<nav id="FooterNav">
			<?php include 'lib/partials/_nav.php' ?>
		</nav>
		<div class="copyright">
			<p>
				Powered by <a href="http://rapleaf.com/">InstantData</a>. 
			</p>
			<p>Need help? Contact our <a href="#">Customer Support</a>. Yes, we have a <a href="#">TOS</a> and <a href="#">Privacy Policy</a>.
			</p>
		</div>
	</div>
</footer>