<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta name="apple-mobile-web-app-capable" content="yes">
<meta name="viewport" content ="width=device-width, initial-scale=1.0, user-scalable=no">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no, maximum-scale=1.0">
<meta name="apple-touch-fullscreen" content="yes">
<meta name="google-site-verification" content="z3_7KzMzHY-tWwrEPZ-ovVsBNQDHJNs5rO372Tx5hZo">
<meta name="author" content="Todd Zaki Warfel">