<link href="/lib/stylesheets/screen.css" rel="stylesheet" media="screen, projection">
<!--[if lte IE 6]><link rel="stylesheet" href="http://universal-ie6-css.googlecode.com/files/ie6.1.0b.css" media="screen, projection"><![endif]-->
<script src="/lib/javascripts/modernizr-2.0.6.min.js"></script>
<script type="text/javascript" src="http://use.typekit.com/vpq2wka.js"></script>
<script type="text/javascript">try{Typekit.load();}catch(e){}</script>