<script src="/lib/js/modernizr-2.0.6.min.js"></script>
<link href="/lib/css/style.css" rel="stylesheet" media="screen, projection">
<!--[if lte IE 6]><link rel="stylesheet" href="http://universal-ie6-css.googlecode.com/files/ie6.1.0b.css" media="screen, projection"><![endif]-->
<link href="/lib/css/hashgrid.css" rel="stylesheet" media="screen, projection">
<!-- plugins -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.6.2/jquery.min.js"></script>
<script src="/lib/js/hashgrid.js"></script> 
<script src="/lib/js/jquery.placeholder.min.js"></script>
<script src="/lib/js/jquery.respond.min.js"></script>
<!-- custom scripts -->
<script src="/lib/js/base.js"></script> 
<script type="text/javascript" src="http://use.typekit.com/utf5kup.js"></script>
<script type="text/javascript">try{Typekit.load();}catch(e){}</script>